# -*- coding: utf-8 -*-
"""ai_music_dj_true_ai_agent_english (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OYpH0Lziu46nLeEzq2_sZ-b-4S8vhA6h

# AI Music DJ — High-Accuracy GTZAN Notebook (Foundation-Model Version)

This notebook is a stronger replacement for the earlier small-CNN version.

It is designed for your current setup:

- **Dataset path**: `/content/drive/MyDrive/EECS6895/finalproject/dataset/genres_original`
- **Goal**: higher genre accuracy on GTZAN, then keep the two project paths:
  1. **Audio → Language**
  2. **Language → Audio**
- **Compute assumption**: GPU is available and you do **not** need a tiny model.

## Why this notebook is different
Instead of training a small CNN from scratch on Mel spectrogram images, this notebook uses a **pretrained audio transformer backbone (AST)** plus **clip-level multi-crop aggregation**.

That design is motivated by recent results showing:
- **Pretrained / transfer-learning-based approaches are much stronger than scratch CNNs on low-resource GTZAN-like setups**
- **AST-style 10-second chunking is a strong low-resource strategy**
- Recent work continues to show that **pretrained audio representations** beat older baselines like PANNs / VGGish on GTZAN

This notebook also keeps your original project idea:
- full-clip **librosa features** for retrieval and explanation
- **Random Forest baseline**
- stronger **foundation-model classifier**
- optional **GPT** recommendation / parsing layer

## Literature notes used to design this notebook

**Why 10-second chunking + a pretrained transformer?**  
A low-resource GTZAN transfer-learning paper using **AST** explicitly states that AST takes **10-second audio input** and chunks GTZAN clips into **non-overlapping 10-second segments**; it reports **new state-of-the-art results on GTZAN** in that low-resource setting.  
Paper: *Low-Resource Music Genre Classification with Cross-Transformer Fine-Tuning and Prompt Tuning* (2022/2023)  
Link: https://arxiv.org/pdf/2211.01317

**Why move away from scratch CNNs?**  
A 2026 study on music genre classification reports that **pretrained SSL embeddings**—especially **BYOL-A**—outperform **PANNs** and **VGGish** on GTZAN, reaching **81.5% accuracy**.  
Paper: *Evaluating Pretrained General-Purpose Audio Representations for Music Genre Classification* (2026)  
Link: https://arxiv.org/abs/2603.13871

**Why keep a music-foundation-model direction in mind?**  
Recent music-specific SSL work such as **MERT** and **MuQ** argues that pretrained music representations transfer strongly across downstream music understanding tasks.  
Papers:
- MERT (2023): https://arxiv.org/abs/2306.00107
- MuQ (2025): https://arxiv.org/abs/2501.01108

**Why the GPT config below defaults to `gpt-5-mini` rather than a generic `gpt-5.1-mini`?**  
OpenAI's public model docs currently expose **`gpt-5.1`** and **`gpt-5 mini`**. I did **not** find a public general-purpose model ID named `gpt-5.1-mini`, so this notebook defaults to **`gpt-5-mini`** for lower cost. If you want more quality, switch one line to **`gpt-5.1`**.  
Docs:
- GPT-5.1: https://developers.openai.com/api/docs/models/gpt-5.1
- GPT-5 mini: https://developers.openai.com/api/docs/models/gpt-5-mini

> This notebook is built to **maximize the odds of getting a strong result in one run**, but no notebook can honestly guarantee a specific final accuracy.
"""

# If running in Colab, mount Drive first.
from google.colab import drive
drive.mount('/content/drive')

!pip -q install -U transformers accelerate librosa soundfile scikit-learn matplotlib openai gradio
!pip -q install pandas==2.2.2

import os, getpass
os.environ["OPENAI_API_KEY"] = getpass.getpass("Enter your OpenAI API key: ")

# =========================
# User configuration
# =========================
from pathlib import Path

DATASET_AUDIO_DIR = Path("/content/drive/MyDrive/EECS6895/finalproject/dataset/genres_original")
CACHE_DIR = Path("/content/drive/MyDrive/EECS6895/finalproject/cache_highacc_ast")
CACHE_DIR.mkdir(parents=True, exist_ok=True)

DISPLAY_NAME_MAP = {
    "blues": "blues",
    "classical": "classical",
    "country": "country",
    "disco": "disco",
    "hiphop": "hip-hop",
    "jazz": "jazz",
    "metal": "metal",
    "pop": "pop",
    "reggae": "reggae",
    "rock": "rock",
}

SEED = 42

FULL_CLIP_SR = 22050
MODEL_SR = 16000
FULL_CLIP_SECONDS = 30.0

SEGMENT_SECONDS = 10.0
TRAIN_CROP_OFFSETS = [0.0, 5.0, 10.0, 15.0, 20.0]
EVAL_CROP_OFFSETS  = [0.0, 5.0, 10.0, 15.0, 20.0]

N_MFCC = 40
RF_N_ESTIMATORS = 800

AST_MODEL_ID = "MIT/ast-finetuned-audioset-10-10-0.4593"
UNFREEZE_LAST_N_AST_BLOCKS = 4
AST_BATCH_SIZE = 8
AST_EPOCHS = 8
AST_BACKBONE_LR = 1e-5
AST_HEAD_LR = 5e-4
AST_WEIGHT_DECAY = 1e-4
AST_EARLY_STOP_PATIENCE = 3
USE_MIXED_PRECISION = True

USE_OPENAI = True
OPENAI_MODEL = "gpt-5-mini"

ENABLE_GRADIO_DEMO = True

print("DATASET_AUDIO_DIR:", DATASET_AUDIO_DIR)
print("CACHE_DIR:", CACHE_DIR)
print("AST_MODEL_ID:", AST_MODEL_ID)
print("OPENAI_MODEL:", OPENAI_MODEL)

import os, json, random, warnings
from collections import defaultdict

import numpy as np
import pandas as pd
import librosa
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

import torch
from torch.utils.data import Dataset, DataLoader
from transformers import AutoFeatureExtractor, ASTForAudioClassification, get_cosine_schedule_with_warmup

warnings.filterwarnings("ignore")

def set_seed(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(SEED)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)
print("cuda:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("gpu:", torch.cuda.get_device_name(0))

AUDIO_EXTS = {".wav", ".au", ".mp3", ".flac", ".ogg"}

def scan_audio_dataset(audio_root):
    rows = []
    for genre_dir in sorted(audio_root.iterdir()):
        if not genre_dir.is_dir():
            continue
        genre_key = genre_dir.name.lower().strip()
        display_genre = DISPLAY_NAME_MAP.get(genre_key, genre_key)
        for fp in sorted(genre_dir.iterdir()):
            if fp.suffix.lower() not in AUDIO_EXTS:
                continue
            rows.append({
                "clip_id": fp.stem,
                "genre_key": genre_key,
                "genre": display_genre,
                "audio_path": str(fp),
            })
    df = pd.DataFrame(rows)
    if df.empty:
        raise ValueError(f"No audio files found under {audio_root}")
    return df

clip_df = scan_audio_dataset(DATASET_AUDIO_DIR)
print("num clips:", len(clip_df))
display(clip_df.head())
display(clip_df["genre"].value_counts().sort_index())

from google.colab import drive
drive.mount('/content/drive')

train_val_df, test_df = train_test_split(
    clip_df,
    test_size=0.20,
    random_state=SEED,
    stratify=clip_df["genre_key"],
)

train_df, val_df = train_test_split(
    train_val_df,
    test_size=0.125,
    random_state=SEED,
    stratify=train_val_df["genre_key"],
)

train_df = train_df.reset_index(drop=True)
val_df = val_df.reset_index(drop=True)
test_df = test_df.reset_index(drop=True)

print("train / val / test sizes:", len(train_df), len(val_df), len(test_df))
display(train_df["genre"].value_counts().sort_index())
display(val_df["genre"].value_counts().sort_index())
display(test_df["genre"].value_counts().sort_index())

"""## Hand-crafted features

These are kept for:
- your **Random Forest baseline**
- retrieval in **Language → Audio**
- interpretable summaries for the DJ-style text output
"""

FULL_FEATURES_CSV = CACHE_DIR / "full_clip_features.csv"

def load_audio_full(path, sr=FULL_CLIP_SR, duration=FULL_CLIP_SECONDS):
    y, _ = librosa.load(path, sr=sr, mono=True, duration=duration)
    target_len = int(sr * duration)
    if len(y) < target_len:
        y = np.pad(y, (0, target_len - len(y)))
    else:
        y = y[:target_len]
    return y

def extract_full_clip_features(path):
    y = load_audio_full(path, sr=FULL_CLIP_SR, duration=FULL_CLIP_SECONDS)
    mfcc = librosa.feature.mfcc(y=y, sr=FULL_CLIP_SR, n_mfcc=N_MFCC)
    rms = librosa.feature.rms(y=y)
    centroid = librosa.feature.spectral_centroid(y=y, sr=FULL_CLIP_SR)
    zcr = librosa.feature.zero_crossing_rate(y)
    tempo, _ = librosa.beat.beat_track(y=y, sr=FULL_CLIP_SR)

    feats = {
        "tempo_bpm": float(tempo),
        "rms_mean": float(rms.mean()),
        "rms_std": float(rms.std()),
        "centroid_mean": float(centroid.mean()),
        "centroid_std": float(centroid.std()),
        "zcr_mean": float(zcr.mean()),
        "zcr_std": float(zcr.std()),
    }
    mfcc_means = mfcc.mean(axis=1)
    mfcc_stds = mfcc.std(axis=1)
    for i in range(N_MFCC):
        feats[f"mfcc_mean_{i}"] = float(mfcc_means[i])
        feats[f"mfcc_std_{i}"] = float(mfcc_stds[i])
    return feats

if FULL_FEATURES_CSV.exists():
    feature_df = pd.read_csv(FULL_FEATURES_CSV)
    print("Loaded cached features:", FULL_FEATURES_CSV)
else:
    rows = []
    for _, row in clip_df.iterrows():
        feats = extract_full_clip_features(row["audio_path"])
        rows.append({**row.to_dict(), **feats})
    feature_df = pd.DataFrame(rows)
    feature_df.to_csv(FULL_FEATURES_CSV, index=False)
    print("Saved cached features:", FULL_FEATURES_CSV)

print("feature_df size:", len(feature_df))
display(feature_df.head())

feature_cols = [
    c for c in feature_df.columns
    if c.startswith("mfcc_") or c in {"tempo_bpm", "rms_mean", "rms_std", "centroid_mean", "centroid_std", "zcr_mean", "zcr_std"}
]

label_names = sorted(feature_df["genre"].unique())
label2id = {g: i for i, g in enumerate(label_names)}
id2label = {i: g for g, i in label2id.items()}

rf_train_df = feature_df.merge(train_df[["clip_id"]], on="clip_id")
rf_test_df  = feature_df.merge(test_df[["clip_id"]], on="clip_id")

X_train_rf = rf_train_df[feature_cols].values
y_train_rf = rf_train_df["genre"].map(label2id).values
X_test_rf  = rf_test_df[feature_cols].values
y_test_rf  = rf_test_df["genre"].map(label2id).values

rf_model = RandomForestClassifier(
    n_estimators=RF_N_ESTIMATORS,
    max_features="sqrt",
    random_state=SEED,
    n_jobs=-1,
)
rf_model.fit(X_train_rf, y_train_rf)
rf_test_pred = rf_model.predict(X_test_rf)
rf_test_acc = accuracy_score(y_test_rf, rf_test_pred)

print("Random Forest test accuracy:", round(rf_test_acc, 4))
print(classification_report(y_test_rf, rf_test_pred, target_names=label_names))

"""## Advanced classifier — pretrained AST with multi-crop clip aggregation"""

def build_segment_df(split_df, offsets):
    rows = []
    for _, row in split_df.iterrows():
        for off in offsets:
            rows.append({
                "clip_id": row["clip_id"],
                "genre": row["genre"],
                "genre_key": row["genre_key"],
                "audio_path": row["audio_path"],
                "offset_sec": float(off),
            })
    return pd.DataFrame(rows)

train_seg_df = build_segment_df(train_df, TRAIN_CROP_OFFSETS)
val_seg_df   = build_segment_df(val_df, EVAL_CROP_OFFSETS)
test_seg_df  = build_segment_df(test_df, EVAL_CROP_OFFSETS)

print("train segments:", len(train_seg_df))
print("val segments  :", len(val_seg_df))
print("test segments :", len(test_seg_df))
display(train_seg_df.head())

feature_extractor = AutoFeatureExtractor.from_pretrained(AST_MODEL_ID)

def load_audio_segment(path, start_sec, duration_sec, sr=MODEL_SR):
    y, _ = librosa.load(path, sr=sr, mono=True, offset=start_sec, duration=duration_sec)
    target_len = int(sr * duration_sec)
    if len(y) < target_len:
        y = np.pad(y, (0, target_len - len(y)))
    else:
        y = y[:target_len]
    return y.astype(np.float32)

class ASTSegmentDataset(Dataset):
    def __init__(self, segment_df, label2id, feature_extractor, training=False):
        self.df = segment_df.reset_index(drop=True)
        self.label2id = label2id
        self.feature_extractor = feature_extractor
        self.training = training

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        y = load_audio_segment(row["audio_path"], row["offset_sec"], SEGMENT_SECONDS, sr=MODEL_SR)

        if self.training:
            gain = np.random.uniform(0.85, 1.15)
            y = y * gain
            if np.random.rand() < 0.25:
                noise = np.random.normal(0, 0.002, size=y.shape).astype(np.float32)
                y = y + noise

        inputs = feature_extractor(y, sampling_rate=MODEL_SR, return_tensors="pt")
        input_values = inputs["input_values"].squeeze(0)
        label = self.label2id[row["genre"]]

        return {
            "input_values": input_values,
            "labels": torch.tensor(label, dtype=torch.long),
            "clip_id": row["clip_id"],
            "genre": row["genre"],
        }

def collate_ast(batch):
    return {
        "input_values": torch.stack([x["input_values"] for x in batch]),
        "labels": torch.stack([x["labels"] for x in batch]),
        "clip_ids": [x["clip_id"] for x in batch],
        "genres": [x["genre"] for x in batch],
    }

train_dataset = ASTSegmentDataset(train_seg_df, label2id, feature_extractor, training=True)
val_dataset   = ASTSegmentDataset(val_seg_df, label2id, feature_extractor, training=False)
test_dataset  = ASTSegmentDataset(test_seg_df, label2id, feature_extractor, training=False)

train_loader = DataLoader(train_dataset, batch_size=AST_BATCH_SIZE, shuffle=True, num_workers=2, collate_fn=collate_ast, pin_memory=True)
val_loader   = DataLoader(val_dataset, batch_size=AST_BATCH_SIZE, shuffle=False, num_workers=2, collate_fn=collate_ast, pin_memory=True)
test_loader  = DataLoader(test_dataset, batch_size=AST_BATCH_SIZE, shuffle=False, num_workers=2, collate_fn=collate_ast, pin_memory=True)

sample_batch = next(iter(train_loader))
print("input batch shape:", sample_batch["input_values"].shape)
print("label batch shape:", sample_batch["labels"].shape)

model = ASTForAudioClassification.from_pretrained(
    AST_MODEL_ID,
    num_labels=len(label_names),
    label2id=label2id,
    id2label=id2label,
    ignore_mismatched_sizes=True,
)

for p in model.audio_spectrogram_transformer.parameters():
    p.requires_grad = False

encoder_layers = model.audio_spectrogram_transformer.encoder.layer
for layer in encoder_layers[-UNFREEZE_LAST_N_AST_BLOCKS:]:
    for p in layer.parameters():
        p.requires_grad = True

for p in model.classifier.parameters():
    p.requires_grad = True

model.to(device)

n_total = sum(p.numel() for p in model.parameters())
n_trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Total params: {n_total:,}")
print(f"Trainable params: {n_trainable:,}")

backbone_params, head_params = [], []
for name, p in model.named_parameters():
    if not p.requires_grad:
        continue
    if "classifier" in name:
        head_params.append(p)
    else:
        backbone_params.append(p)

optimizer = torch.optim.AdamW(
    [
        {"params": backbone_params, "lr": AST_BACKBONE_LR},
        {"params": head_params, "lr": AST_HEAD_LR},
    ],
    weight_decay=AST_WEIGHT_DECAY,
)

num_training_steps = AST_EPOCHS * len(train_loader)
num_warmup_steps = max(1, int(0.1 * num_training_steps))
scheduler = get_cosine_schedule_with_warmup(
    optimizer,
    num_warmup_steps=num_warmup_steps,
    num_training_steps=num_training_steps,
)

scaler = torch.cuda.amp.GradScaler(enabled=(USE_MIXED_PRECISION and torch.cuda.is_available()))

def aggregate_clip_probs(clip_ids, probs_np):
    clip_to_probs = defaultdict(list)
    for cid, p in zip(clip_ids, probs_np):
        clip_to_probs[cid].append(p)
    return {cid: np.mean(np.stack(arrs, axis=0), axis=0) for cid, arrs in clip_to_probs.items()}

def evaluate_loader(model, loader, true_clip_df):
    model.eval()
    all_losses, all_probs = [], []
    all_labels, all_clip_ids = [], []

    with torch.no_grad():
        for batch in loader:
            input_values = batch["input_values"].to(device)
            labels = batch["labels"].to(device)

            with torch.cuda.amp.autocast(enabled=(USE_MIXED_PRECISION and torch.cuda.is_available())):
                outputs = model(input_values=input_values, labels=labels)
                loss = outputs.loss
                logits = outputs.logits

            probs = torch.softmax(logits, dim=-1).detach().cpu().numpy()
            all_losses.append(loss.item())
            all_probs.append(probs)
            all_labels.extend(labels.detach().cpu().tolist())
            all_clip_ids.extend(batch["clip_ids"])

    all_probs = np.concatenate(all_probs, axis=0)
    seg_pred = all_probs.argmax(axis=1)
    seg_acc = accuracy_score(all_labels, seg_pred)

    clip_prob_map = aggregate_clip_probs(all_clip_ids, all_probs)
    clip_truth = true_clip_df.set_index("clip_id")["genre"].to_dict()

    clip_ids_sorted = sorted(clip_prob_map.keys())
    clip_probs = np.stack([clip_prob_map[cid] for cid in clip_ids_sorted], axis=0)
    clip_pred = clip_probs.argmax(axis=1)
    clip_true = np.array([label2id[clip_truth[cid]] for cid in clip_ids_sorted])

    clip_acc = accuracy_score(clip_true, clip_pred)

    return {
        "loss": float(np.mean(all_losses)),
        "seg_acc": float(seg_acc),
        "clip_acc": float(clip_acc),
        "clip_true": clip_true,
        "clip_pred": clip_pred,
        "clip_probs": clip_probs,
        "clip_ids": clip_ids_sorted,
    }

BEST_MODEL_PATH = CACHE_DIR / "best_ast_gztan.pt"

best_val_clip_acc = -1.0
best_epoch = -1
epochs_without_improve = 0
history = []

for epoch in range(1, AST_EPOCHS + 1):
    model.train()
    train_losses, train_true, train_pred = [], [], []

    for batch in train_loader:
        input_values = batch["input_values"].to(device, non_blocking=True)
        labels = batch["labels"].to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)

        with torch.cuda.amp.autocast(enabled=(USE_MIXED_PRECISION and torch.cuda.is_available())):
            outputs = model(input_values=input_values, labels=labels)
            loss = outputs.loss
            logits = outputs.logits

        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        scaler.step(optimizer)
        scaler.update()
        scheduler.step()

        train_losses.append(loss.item())
        train_true.extend(labels.detach().cpu().tolist())
        train_pred.extend(logits.argmax(dim=-1).detach().cpu().tolist())

    train_acc = accuracy_score(train_true, train_pred)
    train_loss = float(np.mean(train_losses))
    val_metrics = evaluate_loader(model, val_loader, val_df)

    row = {
        "epoch": epoch,
        "train_loss": train_loss,
        "train_acc": float(train_acc),
        "val_loss": val_metrics["loss"],
        "val_seg_acc": val_metrics["seg_acc"],
        "val_clip_acc": val_metrics["clip_acc"],
    }
    history.append(row)
    print(row)

    if val_metrics["clip_acc"] > best_val_clip_acc:
        best_val_clip_acc = val_metrics["clip_acc"]
        best_epoch = epoch
        epochs_without_improve = 0
        torch.save(model.state_dict(), BEST_MODEL_PATH)
    else:
        epochs_without_improve += 1

    if epochs_without_improve >= AST_EARLY_STOP_PATIENCE:
        print(f"Early stopping at epoch {epoch}. Best epoch: {best_epoch}")
        break

history_df = pd.DataFrame(history)
display(history_df)
print("Best val clip accuracy:", best_val_clip_acc)
print("Best epoch:", best_epoch)

model.load_state_dict(torch.load(BEST_MODEL_PATH, map_location=device))
test_metrics = evaluate_loader(model, test_loader, test_df)

print("AST test segment accuracy:", round(test_metrics["seg_acc"], 4))
print("AST test clip accuracy   :", round(test_metrics["clip_acc"], 4))
print()
print(classification_report(test_metrics["clip_true"], test_metrics["clip_pred"], target_names=label_names))

fig, ax = plt.subplots(1, 2, figsize=(12, 4))
ax[0].plot(history_df["epoch"], history_df["train_loss"], marker="o", label="train_loss")
ax[0].plot(history_df["epoch"], history_df["val_loss"], marker="o", label="val_loss")
ax[0].set_title("Loss")
ax[0].legend()

ax[1].plot(history_df["epoch"], history_df["train_acc"], marker="o", label="train_acc")
ax[1].plot(history_df["epoch"], history_df["val_clip_acc"], marker="o", label="val_clip_acc")
ax[1].set_title("Accuracy")
ax[1].legend()
plt.show()

cm = confusion_matrix(test_metrics["clip_true"], test_metrics["clip_pred"])
fig, ax = plt.subplots(figsize=(8, 6))
im = ax.imshow(cm)
ax.set_xticks(range(len(label_names)))
ax.set_yticks(range(len(label_names)))
ax.set_xticklabels(label_names, rotation=45, ha="right")
ax.set_yticklabels(label_names)
ax.set_xlabel("Predicted")
ax.set_ylabel("True")
ax.set_title("AST clip-level confusion matrix")
plt.colorbar(im, ax=ax)
plt.show()

metrics_to_save = {
    "rf_test_acc": float(rf_test_acc),
    "ast_test_segment_acc": float(test_metrics["seg_acc"]),
    "ast_test_clip_acc": float(test_metrics["clip_acc"]),
    "label_names": label_names,
}
with open(CACHE_DIR / "final_metrics.json", "w") as f:
    json.dump(metrics_to_save, f, indent=2)
print("Saved metrics to", CACHE_DIR / "final_metrics.json")
print("Saved model to  ", BEST_MODEL_PATH)

"""## Path 1 — Audio → Language"""

openai_client = None
if USE_OPENAI:
    if "OPENAI_API_KEY" not in os.environ:
        raise EnvironmentError("Set OPENAI_API_KEY before using USE_OPENAI=True.")
    from openai import OpenAI
    openai_client = OpenAI()
    print("OpenAI client ready.")
else:
    print("USE_OPENAI=False -> template fallback will be used.")

def compute_single_clip_feature_summary(audio_path):
    return extract_full_clip_features(audio_path)

def predict_clip_with_ast(audio_path, offsets=EVAL_CROP_OFFSETS):
    model.eval()
    all_probs = []
    with torch.no_grad():
        for off in offsets:
            y = load_audio_segment(audio_path, off, SEGMENT_SECONDS, sr=MODEL_SR)
            inputs = feature_extractor(y, sampling_rate=MODEL_SR, return_tensors="pt")
            input_values = inputs["input_values"].to(device)
            with torch.cuda.amp.autocast(enabled=(USE_MIXED_PRECISION and torch.cuda.is_available())):
                logits = model(input_values=input_values).logits
            probs = torch.softmax(logits, dim=-1).detach().cpu().numpy()[0]
            all_probs.append(probs)
    mean_probs = np.mean(np.stack(all_probs, axis=0), axis=0)
    pred_id = int(mean_probs.argmax())
    pred_genre = id2label[pred_id]
    top3_idx = np.argsort(mean_probs)[::-1][:3]
    top3 = [(id2label[i], float(mean_probs[i])) for i in top3_idx]
    return {"pred_id": pred_id, "pred_genre": pred_genre, "probs": mean_probs, "top3": top3}

def template_dj_recommendation(pred_genre, feats, top3):
    tempo = feats["tempo_bpm"]
    centroid = feats["centroid_mean"]
    rms = feats["rms_mean"]

    if tempo < 85:
        tempo_desc = "slow"
    elif tempo < 120:
        tempo_desc = "moderate"
    else:
        tempo_desc = "fast"

    if rms < feature_df["rms_mean"].quantile(0.33):
        energy_desc = "soft"
    elif rms < feature_df["rms_mean"].quantile(0.66):
        energy_desc = "balanced"
    else:
        energy_desc = "high-energy"

    if centroid < feature_df["centroid_mean"].quantile(0.33):
        tone_desc = "warm"
    elif centroid < feature_df["centroid_mean"].quantile(0.66):
        tone_desc = "balanced"
    else:
        tone_desc = "bright"

    return (
        f"This track leans {pred_genre} with a {tempo_desc} tempo around {tempo:.1f} BPM, "
        f"{energy_desc} dynamics, and a {tone_desc} spectral profile. "
        f"It fits a listener who wants a {pred_genre}-styled mood with a clear sonic identity."
    )

def llm_dj_recommendation(pred_genre, feats, top3):
    if (not USE_OPENAI) or (openai_client is None):
        return template_dj_recommendation(pred_genre, feats, top3)

    prompt = f'''
You are an AI music DJ.
Write a concise, vivid recommendation paragraph in natural English.

Model prediction:
- primary_genre: {pred_genre}
- top3_predictions: {top3}

Audio features:
- tempo_bpm: {feats["tempo_bpm"]:.2f}
- rms_mean: {feats["rms_mean"]:.6f}
- centroid_mean: {feats["centroid_mean"]:.2f}
- zcr_mean: {feats["zcr_mean"]:.6f}

Constraints:
- 2 to 4 sentences
- Sound like a DJ or playlist curator
- Mention the mood / atmosphere
- Do not invent exact artist metadata for the GTZAN clip
'''
    response = openai_client.responses.create(model=OPENAI_MODEL, input=prompt)
    return response.output_text.strip()

def analyze_audio_path(audio_path):
    pred = predict_clip_with_ast(audio_path)
    feats = compute_single_clip_feature_summary(audio_path)
    rec = llm_dj_recommendation(pred["pred_genre"], feats, pred["top3"])
    return {"prediction": pred, "features": feats, "recommendation": rec}

demo_audio_path = test_df.iloc[0]["audio_path"]
demo_result = analyze_audio_path(demo_audio_path)

print("Audio path:", demo_audio_path)
print("Predicted genre:", demo_result["prediction"]["pred_genre"])
print("Top-3:", demo_result["prediction"]["top3"])
print()
print("Feature summary:")
for k in ["tempo_bpm", "rms_mean", "centroid_mean", "zcr_mean"]:
    if k == "tempo_bpm":
        print(f"  {k}: {demo_result['features'][k]:.2f}")
    else:
        print(f"  {k}: {demo_result['features'][k]:.4f}")
print()
print("DJ recommendation:")
print(demo_result["recommendation"])

"""## Path 2 — Language → Audio"""

retrieval_df = feature_df.copy()
retrieval_numeric_cols = ["tempo_bpm", "rms_mean", "centroid_mean", "zcr_mean"]
retrieval_stats = {
    c: {"mean": retrieval_df[c].mean(), "std": max(retrieval_df[c].std(), 1e-8)}
    for c in retrieval_numeric_cols
}

def zscore_value(x, col):
    return (x - retrieval_stats[col]["mean"]) / retrieval_stats[col]["std"]

for c in retrieval_numeric_cols:
    retrieval_df[f"{c}_z"] = retrieval_df[c].apply(lambda x: zscore_value(x, c))

display(retrieval_df[["clip_id", "genre", "tempo_bpm", "rms_mean", "centroid_mean"]].head())

def parse_text_to_targets_rule_based(user_text):
    text = user_text.lower()

    preferred_genres = []
    for g in label_names:
        if g in text:
            preferred_genres.append(g)
    if "hip hop" in text or "hip-hop" in text:
        preferred_genres.append("hip-hop")

    tempo = retrieval_df["tempo_bpm"].median()
    rms = retrieval_df["rms_mean"].median()
    centroid = retrieval_df["centroid_mean"].median()

    if any(w in text for w in ["relax", "calm", "late night", "study", "soft", "chill", "mellow"]):
        tempo = retrieval_df["tempo_bpm"].quantile(0.25)
        rms = retrieval_df["rms_mean"].quantile(0.25)
        centroid = retrieval_df["centroid_mean"].quantile(0.30)

    if any(w in text for w in ["energetic", "party", "dance", "workout", "fast", "hype"]):
        tempo = retrieval_df["tempo_bpm"].quantile(0.75)
        rms = retrieval_df["rms_mean"].quantile(0.75)
        centroid = retrieval_df["centroid_mean"].quantile(0.70)

    if any(w in text for w in ["bright", "sparkling", "crispy"]):
        centroid = retrieval_df["centroid_mean"].quantile(0.80)

    if any(w in text for w in ["warm", "smooth", "night", "cozy"]):
        centroid = retrieval_df["centroid_mean"].quantile(0.25)

    return {
        "tempo_bpm": float(tempo),
        "rms_mean": float(rms),
        "centroid_mean": float(centroid),
        "preferred_genres": preferred_genres,
        "explanation": "Rule-based fallback parser."
    }

def parse_json_from_text(s):
    s = s.strip()
    start = s.find("{")
    end = s.rfind("}")
    if start == -1 or end == -1:
        raise ValueError("No JSON object found in LLM output.")
    return json.loads(s[start:end+1])

def parse_text_to_targets_llm(user_text):
    if (not USE_OPENAI) or (openai_client is None):
        return parse_text_to_targets_rule_based(user_text)

    prompt = f'''
Convert the following music request into retrieval targets.
Return JSON only.

Allowed genres: {label_names}

Required JSON keys:
- tempo_bpm
- rms_mean
- centroid_mean
- preferred_genres
- explanation

The feature ranges should stay realistic for this dataset:
- tempo_bpm roughly between {retrieval_df["tempo_bpm"].min():.2f} and {retrieval_df["tempo_bpm"].max():.2f}
- rms_mean roughly between {retrieval_df["rms_mean"].min():.6f} and {retrieval_df["rms_mean"].max():.6f}
- centroid_mean roughly between {retrieval_df["centroid_mean"].min():.2f} and {retrieval_df["centroid_mean"].max():.2f}

User request:
{user_text}
'''
    response = openai_client.responses.create(model=OPENAI_MODEL, input=prompt)
    return parse_json_from_text(response.output_text)

def retrieve_tracks_from_targets(targets, top_k=5):
    tmp = retrieval_df.copy()

    target_z = {
        "tempo_bpm_z": zscore_value(targets["tempo_bpm"], "tempo_bpm"),
        "rms_mean_z": zscore_value(targets["rms_mean"], "rms_mean"),
        "centroid_mean_z": zscore_value(targets["centroid_mean"], "centroid_mean"),
    }

    tmp["retrieval_distance"] = (
        1.20 * (tmp["tempo_bpm_z"] - target_z["tempo_bpm_z"]) ** 2 +
        1.00 * (tmp["rms_mean_z"] - target_z["rms_mean_z"]) ** 2 +
        1.10 * (tmp["centroid_mean_z"] - target_z["centroid_mean_z"]) ** 2
    ) ** 0.5

    preferred = set(targets.get("preferred_genres", []))
    tmp["genre_bonus"] = tmp["genre"].apply(lambda g: -0.35 if g in preferred else 0.0) if preferred else 0.0
    tmp["final_score"] = tmp["retrieval_distance"] + tmp["genre_bonus"]

    cols = ["clip_id", "genre", "audio_path", "tempo_bpm", "rms_mean", "centroid_mean", "final_score"]
    return tmp.sort_values("final_score", ascending=True)[cols].head(top_k).reset_index(drop=True)

def final_dj_response_for_query(user_text, targets, retrieved_df):
    if (not USE_OPENAI) or (openai_client is None):
        top_row = retrieved_df.iloc[0]
        return (
            f'For the request "{user_text}", the system matched tracks closest to '
            f'{top_row["genre"]} with tempo around {top_row["tempo_bpm"]:.1f} BPM '
            f'and centroid around {top_row["centroid_mean"]:.1f}.'
        )

    table_text = retrieved_df.to_string(index=False)
    prompt = f'''
You are an AI music DJ.
User request: {user_text}

Parsed targets:
{json.dumps(targets, indent=2)}

Top retrieved tracks:
{table_text}

Write 2 to 4 sentences explaining why these results fit the request.
Do not fabricate song titles beyond the clip ids shown.
'''
    response = openai_client.responses.create(model=OPENAI_MODEL, input=prompt)
    return response.output_text.strip()

"""## True AI Music Agent — dynamic tool-using agent, not a preset recommender

This section replaces the earlier rule-based/planned-demo agent.

The agent below does **not** depend on the GTZAN catalog and does **not** use pre-written question-answer examples. It calls the OpenAI API at runtime and can handle arbitrary natural-language requests, including:

- real-song playlist generation
- task-driven playlist planning
- music discovery questions
- genre/artist/style explanations
- refinement after follow-up messages
- non-playlist music help, when the user asks for it

For playlist requests, it searches the web when useful, recommends real public songs, and runs a critic/reviewer pass before returning the final answer.

**Language policy:** the agent is configured to answer in English only, even when the user prompt is written in another language.

"""

# =========================
# True AI Music Agent
# =========================
# This is the main agent to use.
# It is intentionally not a hard-coded recommender and not a simulated Q&A demo.
# Runtime flow:
#   user message -> OpenAI model with web_search tool -> draft answer
#   -> critic/reviewer pass -> optional repair -> final answer

import os
import json
import getpass
from typing import Any, Dict, List, Optional

try:
    from openai import OpenAI
except ImportError as e:
    raise ImportError("Run the install cell first: !pip -q install -U openai") from e


DEFAULT_MUSIC_AGENT_MODEL = globals().get("OPENAI_MODEL", "gpt-5-mini")


def _ensure_openai_client():
    """Create an OpenAI client, prompting for the API key if needed."""
    global openai_client
    if "OPENAI_API_KEY" not in os.environ or not os.environ["OPENAI_API_KEY"].strip():
        os.environ["OPENAI_API_KEY"] = getpass.getpass("Enter your OpenAI API key: ")
    try:
        openai_client
    except NameError:
        openai_client = None
    if openai_client is None:
        openai_client = OpenAI()
    return openai_client


def _response_output_text(response) -> str:
    """SDK-safe extraction of text from a Responses API result."""
    text = getattr(response, "output_text", None)
    if text:
        return str(text).strip()

    parts = []
    for item in getattr(response, "output", []) or []:
        for content in getattr(item, "content", []) or []:
            value = getattr(content, "text", None)
            if value:
                parts.append(str(value))
    return "\n".join(parts).strip()


def _extract_response_url_citations(response) -> List[Dict[str, str]]:
    """Best-effort extraction of web citation URLs from a Responses API result."""
    citations = []
    seen = set()

    for item in getattr(response, "output", []) or []:
        for content in getattr(item, "content", []) or []:
            for ann in getattr(content, "annotations", []) or []:
                url = getattr(ann, "url", None)
                title = getattr(ann, "title", None)

                nested = getattr(ann, "url_citation", None)
                if nested is not None:
                    url = url or getattr(nested, "url", None)
                    title = title or getattr(nested, "title", None)

                if url and url not in seen:
                    citations.append({"title": title or "", "url": url})
                    seen.add(url)

    return citations


def _dedupe_citations(citations: List[Dict[str, str]]) -> List[Dict[str, str]]:
    out = []
    seen = set()
    for c in citations or []:
        url = (c or {}).get("url")
        if not url or url in seen:
            continue
        out.append({"title": (c or {}).get("title", ""), "url": url})
        seen.add(url)
    return out


def _format_conversation_history(conversation_history: Optional[List[Any]]) -> str:
    """Accepts Gradio-style tuples or OpenAI-style dicts and turns them into plain text context."""
    if not conversation_history:
        return ""

    lines = []
    for turn in conversation_history:
        if isinstance(turn, dict):
            role = turn.get("role", "unknown")
            content = turn.get("content", "")
            if content:
                lines.append(f"{role}: {content}")
        elif isinstance(turn, (list, tuple)) and len(turn) >= 2:
            user_msg, assistant_msg = turn[0], turn[1]
            if user_msg:
                lines.append(f"user: {user_msg}")
            if assistant_msg:
                lines.append(f"assistant: {assistant_msg}")
        else:
            lines.append(str(turn))
    return "\n".join(lines).strip()


def _safe_json_loads_from_model_text(text: str) -> Dict[str, Any]:
    """Parse a JSON object from model text that may accidentally include code fences."""
    if not isinstance(text, str):
        raise ValueError("Model output is not a string.")
    s = text.strip()
    if s.startswith("```"):
        s = s.strip("`").strip()
        if s.lower().startswith("json"):
            s = s[4:].strip()

    start = s.find("{")
    end = s.rfind("}")
    if start < 0 or end <= start:
        raise ValueError("No JSON object found in model output:\n" + text[:1000])
    return json.loads(s[start:end + 1])


def _create_response(
    *,
    instructions: str,
    input_text: str,
    model: Optional[str] = None,
    use_web_search: bool = True,
    search_context_size: str = "medium",
):
    """Create a Responses API call, with fallback for accounts using web_search_preview."""
    client = _ensure_openai_client()
    model = model or DEFAULT_MUSIC_AGENT_MODEL

    kwargs = {
        "model": model,
        "instructions": instructions,
        "input": input_text,
    }

    if use_web_search:
        kwargs["tools"] = [{"type": "web_search", "search_context_size": search_context_size}]
        kwargs["tool_choice"] = "auto"

    try:
        return client.responses.create(**kwargs)
    except Exception as first_error:
        if not use_web_search:
            raise

        # Some environments/accounts still expose the preview tool name.
        kwargs["tools"] = [{"type": "web_search_preview", "search_context_size": search_context_size}]
        try:
            return client.responses.create(**kwargs)
        except Exception as second_error:
            raise RuntimeError(
                "Responses API call failed with both web_search and web_search_preview.\n"
                f"web_search error: {first_error}\n"
                f"web_search_preview error: {second_error}"
            )


MUSIC_AGENT_INSTRUCTIONS = """
You are a general AI music agent with web-search access.

Core behavior:
- You are not a static recommender, not a nearest-neighbor retrieval wrapper, and not a preset Q&A demo.
- Answer the user's actual message dynamically.
- The user may ask for a playlist, music discovery, genre explanation, artist/song comparison, audio/DJ advice, or a general follow-up.
- If the request is about recommending music, recommend real publicly released songs and artists. Do not require the songs to exist in any local dataset.
- Use web search when useful for real song titles, artist names, language, style, era, current popularity, or factual grounding.
- If the request is underspecified and force_answer is true, make reasonable assumptions, state them, and answer anyway.
- If force_answer is false and the request is impossible to answer responsibly without more information, ask at most three concise clarification questions.
- For task-driven playlists, plan the listening arc first: context, phase structure, energy curve, diversity, hard exclusions, and transition logic.
- For playlist output, include song title, artist, and a short reason. If relevant, group by stage.
- Respect negative constraints such as "not too noisy", "not too depressing", "no metal", language constraints, vocal preference, activity context, and duration.
- Do not fabricate certainty. If a criterion cannot be verified, state the uncertainty briefly.
- Always answer in English, regardless of the language used in the user message.
- Keep the final answer useful and direct.
- If the user writes in another language, interpret the request accurately but produce the final response in English.
"""

MUSIC_AGENT_CRITIC_INSTRUCTIONS = """
You are the critic/reviewer for an AI music agent.

Review the draft answer against the user request. Focus on:
- Did it answer the actual request, rather than a preset example?
- For playlist requests, are the songs real and plausible?
- Are hard negative constraints respected?
- Does the answer handle duration, activity context, language, mood, and energy curve when provided?
- Is the playlist too homogeneous or poorly ordered?
- Are assumptions and uncertainty disclosed when needed?
- Did it ask unnecessary clarification instead of answering when force_answer is true?

Return JSON only:
{
  "needs_revision": true or false,
  "issues": ["..."],
  "repair_instructions": ["..."],
  "passed_checks": ["..."]
}
"""

MUSIC_AGENT_REPAIR_INSTRUCTIONS = """
You are the final-answer writer for an AI music agent.

Use the original user request, the draft answer, and the critic review to produce a corrected final answer.
Do not mention internal implementation details.
Always write the final answer in English.
For playlist requests, output real song titles and artists, ordered with a clear listening logic.
When assumptions are necessary, state them briefly at the top.
"""


def run_music_ai_agent(
    user_message: str,
    conversation_history: Optional[List[Any]] = None,
    *,
    force_answer: bool = True,
    use_web_search: bool = True,
    enable_critic: bool = True,
    model: Optional[str] = None,
    search_context_size: str = "medium",
) -> Dict[str, Any]:
    """
    Run the true AI music agent.

    Parameters
    ----------
    user_message:
        Any natural-language request.
    conversation_history:
        Optional previous turns. Accepts Gradio tuples or dicts like {"role": "user", "content": "..."}.
    force_answer:
        True means the agent should make assumptions and answer instead of blocking on clarification.
    use_web_search:
        True enables web search for real songs/facts. Use False only for offline testing.
    enable_critic:
        True runs a second model call to review the draft, then repairs if needed.
    model:
        OpenAI model name. Defaults to OPENAI_MODEL if defined, else gpt-5-mini.
    search_context_size:
        "low", "medium", or "high".
    """
    user_message = (user_message or "").strip()
    if not user_message:
        return {
            "status": "needs_input",
            "answer_markdown": "Please enter a music question or playlist request first.",
            "draft_answer": "",
            "critic_review": {},
            "web_citations": [],
        }

    history_text = _format_conversation_history(conversation_history)
    agent_input = f"""
Runtime settings:
- force_answer: {str(bool(force_answer)).lower()}
- use_web_search: {str(bool(use_web_search)).lower()}

Conversation history:
{history_text if history_text else "(none)"}

Latest user message:
{user_message}
""".strip()

    draft_response = _create_response(
        instructions=MUSIC_AGENT_INSTRUCTIONS,
        input_text=agent_input,
        model=model,
        use_web_search=use_web_search,
        search_context_size=search_context_size,
    )
    draft_answer = _response_output_text(draft_response)
    citations = _extract_response_url_citations(draft_response)

    critic_review = {
        "needs_revision": False,
        "issues": [],
        "repair_instructions": [],
        "passed_checks": [],
    }
    final_answer = draft_answer

    if enable_critic:
        review_input = json.dumps(
            {
                "runtime_settings": {
                    "force_answer": bool(force_answer),
                    "use_web_search": bool(use_web_search),
                },
                "conversation_history": history_text,
                "latest_user_message": user_message,
                "draft_answer": draft_answer,
            },
            ensure_ascii=False,
            indent=2,
        )

        review_response = _create_response(
            instructions=MUSIC_AGENT_CRITIC_INSTRUCTIONS,
            input_text=review_input,
            model=model,
            use_web_search=False,
            search_context_size=search_context_size,
        )
        review_text = _response_output_text(review_response)

        try:
            critic_review = _safe_json_loads_from_model_text(review_text)
        except Exception:
            critic_review = {
                "needs_revision": False,
                "issues": ["Critic JSON could not be parsed; keeping draft answer."],
                "repair_instructions": [],
                "passed_checks": [],
                "raw_review_text": review_text,
            }

        if critic_review.get("needs_revision"):
            repair_input = json.dumps(
                {
                    "conversation_history": history_text,
                    "latest_user_message": user_message,
                    "draft_answer": draft_answer,
                    "critic_review": critic_review,
                },
                ensure_ascii=False,
                indent=2,
            )
            repair_response = _create_response(
                instructions=MUSIC_AGENT_REPAIR_INSTRUCTIONS,
                input_text=repair_input,
                model=model,
                use_web_search=use_web_search,
                search_context_size=search_context_size,
            )
            final_answer = _response_output_text(repair_response)
            citations.extend(_extract_response_url_citations(repair_response))

    return {
        "status": "answered",
        "answer_markdown": final_answer,
        "draft_answer": draft_answer,
        "critic_review": critic_review,
        "web_citations": _dedupe_citations(citations),
        "model": model or DEFAULT_MUSIC_AGENT_MODEL,
        "force_answer": bool(force_answer),
        "use_web_search": bool(use_web_search),
    }


def print_music_agent_result(result: Dict[str, Any], show_debug: bool = False):
    """Convenience display function for notebook usage."""
    print(result.get("answer_markdown", ""))

    if show_debug:
        print("\n--- Critic review ---")
        print(json.dumps(result.get("critic_review", {}), ensure_ascii=False, indent=2))
        if result.get("web_citations"):
            print("\n--- Web citations extracted by API ---")
            for c in result["web_citations"]:
                title = c.get("title") or "(untitled)"
                print(f"- {title}: {c.get('url')}")

# ============================================================
# True AI Music Agent definition
# Run this cell BEFORE launching the Gradio UI.
# ============================================================

import os
import json
import traceback
from openai import OpenAI

# You can override this in Colab before running:
# os.environ["MUSIC_AGENT_MODEL"] = "gpt-5.5"
MUSIC_AGENT_MODEL = os.environ.get("MUSIC_AGENT_MODEL", "gpt-5.5")


def _get_openai_client():
    """
    Create an OpenAI client.
    Make sure OPENAI_API_KEY is set before calling the agent.
    """
    api_key = os.environ.get("OPENAI_API_KEY")

    if not api_key:
        raise EnvironmentError(
            "OPENAI_API_KEY is not set. Run: os.environ['OPENAI_API_KEY'] = 'your_api_key_here'"
        )

    return OpenAI(
        api_key=api_key,
        timeout=60.0,
        max_retries=1,
    )


MUSIC_AGENT_SYSTEM_PROMPT = """
You are a true AI music planning agent, not a preset playlist template.

Always answer in English.

Your job is to help the user with any music-related request:
- build playlists,
- recommend real songs,
- explain genres,
- compare artists,
- adapt a playlist to a task,
- revise previous recommendations,
- answer follow-up questions,
- or ask clarification questions when needed.

When the user asks for a playlist, behave like a planning agent:
1. Understand the user task and constraints.
2. Infer missing details when safe.
3. If force_answer is enabled, do not block on clarification; state your assumptions briefly.
4. Plan the playlist structure.
5. Recommend real songs and real artists.
6. Explain why each song fits.
7. Avoid over-homogeneous recommendations unless the user specifically wants that.
8. Avoid violating explicit negative preferences.
9. If the user asks for a specific language, mood, decade, country, or usage scenario, respect it.

For playlist output, prefer this structure:

Assumptions:
- ...

Playlist:
1. "Song Title" — Artist
   Why it fits: ...
   Placement: ...

Notes:
- ...

If web search is available, use it to verify current or specific song/artist information when useful.
If web search is not available, still give a useful answer from general music knowledge, but say when you are not verifying live availability.
"""


MUSIC_AGENT_CRITIC_PROMPT = """
You are a critic/reviewer for a music recommendation agent.

Review the draft answer against the user's request.

Check:
1. Did the answer satisfy the user's explicit constraints?
2. Did it recommend real songs and artists when a playlist was requested?
3. Is the playlist too homogeneous?
4. Did it ignore any negative preference?
5. Did it make unsupported claims?
6. Should the agent ask a clarification question, or is it acceptable to proceed with assumptions?

Return JSON only:
{
  "status": "ok" or "needs_repair",
  "issues": ["..."],
  "repair_instruction": "..."
}
"""


def _format_conversation_for_prompt(conversation_history, current_message):
    """
    Convert stored conversation history into a simple plain-text context block.
    This avoids Gradio Chatbot format incompatibilities.
    """
    lines = []

    for msg in conversation_history or []:
        role = msg.get("role", "user")
        content = msg.get("content", "")

        if not content:
            continue

        role_name = "USER" if role == "user" else "ASSISTANT"
        lines.append(f"{role_name}:\n{content}")

    lines.append(f"USER:\n{current_message}")

    return "\n\n---\n\n".join(lines)


def _safe_json_loads(text):
    try:
        return json.loads(text)
    except Exception:
        return {
            "status": "needs_repair",
            "issues": ["Critic did not return valid JSON."],
            "repair_instruction": "Improve the answer and make it more directly aligned with the user request.",
            "raw": text,
        }


def _extract_web_citations(response):
    """
    Best-effort extraction of URL citations from Responses API output.
    This is optional debug information for the Gradio panel.
    """
    citations = []

    try:
        for item in getattr(response, "output", []) or []:
            content_list = getattr(item, "content", []) or []

            for content in content_list:
                annotations = getattr(content, "annotations", []) or []

                for ann in annotations:
                    ann_type = getattr(ann, "type", None)

                    if ann_type == "url_citation":
                        citations.append(
                            {
                                "title": getattr(ann, "title", None),
                                "url": getattr(ann, "url", None),
                            }
                        )
    except Exception:
        pass

    return citations


def _create_response(
    client,
    *,
    model,
    instructions,
    input_text,
    use_web_search=False,
    max_output_tokens=900,
):
    """
    Wrapper around client.responses.create().
    Uses web_search only when requested.
    """
    kwargs = {
        "model": model,
        "instructions": instructions,
        "input": input_text,
        "max_output_tokens": max_output_tokens,
    }

    if use_web_search:
        kwargs["tools"] = [{"type": "web_search"}]
        kwargs["tool_choice"] = "auto"
        kwargs["include"] = ["web_search_call.action.sources"]

    try:
        return client.responses.create(**kwargs)

    except TypeError:
        # Fallback for environments with older SDK parameter support.
        kwargs.pop("include", None)
        kwargs.pop("tool_choice", None)
        return client.responses.create(**kwargs)


def run_music_ai_agent(
    message,
    conversation_history=None,
    force_answer=True,
    use_web_search=True,
    enable_critic=False,
    search_context_size="low",
    max_output_tokens=900,
):
    """
    Main AI music agent entry point used by the Gradio UI.

    This is not a preset recommendation template.
    It calls the model at runtime and optionally uses web search.
    """
    client = _get_openai_client()

    conversation_history = conversation_history or []
    message = (message or "").strip()

    if not message:
        return {
            "status": "empty_input",
            "model": MUSIC_AGENT_MODEL,
            "answer_markdown": "Please enter a music-related request.",
            "critic_review": None,
            "web_citations": [],
        }

    force_text = (
        "Force-answer mode is ON. If the user request is underspecified, make reasonable assumptions and continue. "
        "Only ask a clarification question if answering would be impossible or unsafe."
        if force_answer
        else
        "Force-answer mode is OFF. Ask clarification questions when the request is materially underspecified."
    )

    search_text = (
        f"Web search is enabled. Use it when useful. Search context preference: {search_context_size}."
        if use_web_search
        else
        "Web search is disabled. Use general music knowledge and do not claim live verification."
    )

    input_text = f"""
{force_text}

{search_text}

Conversation:
{_format_conversation_for_prompt(conversation_history, message)}
"""

    response = _create_response(
        client,
        model=MUSIC_AGENT_MODEL,
        instructions=MUSIC_AGENT_SYSTEM_PROMPT,
        input_text=input_text,
        use_web_search=use_web_search,
        max_output_tokens=max_output_tokens,
    )

    draft_answer = getattr(response, "output_text", "") or ""
    web_citations = _extract_web_citations(response)

    critic_review = None
    final_answer = draft_answer

    if enable_critic:
        critic_input = f"""
User request:
{message}

Draft answer:
{draft_answer}

Review the draft according to the critic instructions.
"""

        critic_response = _create_response(
            client,
            model=MUSIC_AGENT_MODEL,
            instructions=MUSIC_AGENT_CRITIC_PROMPT,
            input_text=critic_input,
            use_web_search=False,
            max_output_tokens=500,
        )

        critic_text = getattr(critic_response, "output_text", "") or ""
        critic_review = _safe_json_loads(critic_text)

        if critic_review.get("status") == "needs_repair":
            repair_instruction = critic_review.get(
                "repair_instruction",
                "Repair the answer so it better satisfies the user request.",
            )

            repair_input = f"""
User request:
{message}

Original draft:
{draft_answer}

Critic review:
{json.dumps(critic_review, ensure_ascii=False, indent=2)}

Repair instruction:
{repair_instruction}

Return the improved final answer in English.
"""

            repair_response = _create_response(
                client,
                model=MUSIC_AGENT_MODEL,
                instructions=MUSIC_AGENT_SYSTEM_PROMPT,
                input_text=repair_input,
                use_web_search=use_web_search,
                max_output_tokens=max_output_tokens,
            )

            final_answer = getattr(repair_response, "output_text", "") or draft_answer
            web_citations = web_citations + _extract_web_citations(repair_response)

    return {
        "status": "ok",
        "model": MUSIC_AGENT_MODEL,
        "answer_markdown": final_answer,
        "critic_review": critic_review,
        "web_citations": web_citations,
    }


def print_music_agent_result(result):
    print(result.get("answer_markdown", ""))

test_result = run_music_ai_agent(
    "I want to listen to jazz",
    force_answer=True,
    use_web_search=False,
    enable_critic=False,
)

print_music_agent_result(test_result)

## Optional Gradio demo

ENABLE_GRADIO_DEMO = globals().get("ENABLE_GRADIO_DEMO", True)

if ENABLE_GRADIO_DEMO:
    import json
    import traceback
    import inspect
    import gradio as gr

    try:
        gr.close_all()
    except Exception:
        pass


    def ui_analyze_audio(audio_file):
        if audio_file is None:
            return "No audio uploaded.", "", ""

        if "analyze_audio_path" not in globals():
            return (
                "Audio analysis is not available because analyze_audio_path() is not defined.",
                "",
                "",
            )

        result = analyze_audio_path(audio_file)

        top3 = "\n".join(
            [f"{g}: {p:.3f}" for g, p in result["prediction"]["top3"]]
        )

        feat_text = "\n".join(
            [
                f"{k}: {result['features'][k]:.4f}"
                if k != "tempo_bpm"
                else f"{k}: {result['features'][k]:.2f}"
                for k in ["tempo_bpm", "rms_mean", "centroid_mean", "zcr_mean"]
            ]
        )

        return result["recommendation"], top3, feat_text


    def _call_music_agent_safely(
        message,
        conversation_history,
        force_answer,
        use_web_search,
        enable_critic,
        search_context_size,
    ):
        if "run_music_ai_agent" not in globals():
            raise NameError(
                "run_music_ai_agent() is not defined. Run the agent-definition cells before launching Gradio."
            )

        kwargs = {
            "conversation_history": conversation_history,
            "force_answer": force_answer,
            "use_web_search": use_web_search,
            "enable_critic": enable_critic,
            "search_context_size": search_context_size,
        }

        sig = inspect.signature(run_music_ai_agent)

        if "max_output_tokens" in sig.parameters:
            kwargs["max_output_tokens"] = 900

        return run_music_ai_agent(message, **kwargs)


    def _render_transcript(history):
        if not history:
            return ""

        blocks = []

        for msg in history:
            role = msg.get("role", "")
            content = msg.get("content", "")

            if role == "user":
                blocks.append(f"USER:\n{content}")
            elif role == "assistant":
                blocks.append(f"AGENT:\n{content}")

        return "\n\n" + "\n\n---\n\n".join(blocks)


    def ui_music_agent_chat(
        message,
        conversation_history,
        force_answer,
        use_web_search,
        enable_critic,
        search_context_size,
    ):
        message = (message or "").strip()
        conversation_history = conversation_history or []

        if not message:
            return _render_transcript(conversation_history), "", "{}", conversation_history

        try:
            result = _call_music_agent_safely(
                message=message,
                conversation_history=conversation_history,
                force_answer=force_answer,
                use_web_search=use_web_search,
                enable_critic=enable_critic,
                search_context_size=search_context_size,
            )

            answer = result.get("answer_markdown", "")

            if not answer:
                answer = "The agent returned an empty response."

            debug = json.dumps(
                {
                    "status": result.get("status"),
                    "model": result.get("model"),
                    "critic_review": result.get("critic_review"),
                    "web_citations": result.get("web_citations"),
                },
                ensure_ascii=False,
                indent=2,
            )

        except Exception as e:
            answer = (
                "Agent error.\n\n"
                "Check the debug box below and the notebook output for the full traceback.\n\n"
                f"Error summary: {type(e).__name__}: {e}"
            )

            debug = json.dumps(
                {
                    "error_type": type(e).__name__,
                    "error": str(e),
                    "traceback": traceback.format_exc(),
                },
                ensure_ascii=False,
                indent=2,
            )

        conversation_history = conversation_history + [
            {
                "role": "user",
                "content": message,
            },
            {
                "role": "assistant",
                "content": answer,
            },
        ]

        transcript = _render_transcript(conversation_history)

        return transcript, "", debug, conversation_history


    def ui_clear_chat():
        return "", "", "{}", []


    with gr.Blocks(title="AI Music DJ") as demo:
        gr.Markdown("# AI Music DJ")

        with gr.Tab("True AI Music Agent"):
            gr.Markdown(
                "This is the main interface. It dynamically calls the model and web search at runtime; "
                "it is not a preset recommendation template."
            )

            conversation_state = gr.State([])

            transcript = gr.Textbox(
                label="Conversation",
                lines=22,
                interactive=False,
            )

            message = gr.Textbox(
                label="Ask anything",
                placeholder=(
                    "Example: Make me a 30-minute study playlist. "
                    "First 10 minutes should help me settle in, then keep me focused. "
                    "Avoid loud drum-heavy tracks."
                ),
                lines=3,
            )

            with gr.Row():
                force_answer = gr.Checkbox(
                    value=True,
                    label="Force answer with assumptions instead of blocking on clarification",
                )

                use_web_search = gr.Checkbox(
                    value=True,
                    label="Use web search",
                )

                enable_critic = gr.Checkbox(
                    value=False,
                    label="Run critic/reviewer pass",
                )

            search_context_size = gr.Dropdown(
                choices=["low", "medium", "high"],
                value="low",
                label="Web search context size",
            )

            with gr.Row():
                send = gr.Button("Run agent")
                clear = gr.Button("Clear conversation")

            debug = gr.Code(
                label="Debug / critic review",
                language="json",
            )

            send.click(
                fn=ui_music_agent_chat,
                inputs=[
                    message,
                    conversation_state,
                    force_answer,
                    use_web_search,
                    enable_critic,
                    search_context_size,
                ],
                outputs=[
                    transcript,
                    message,
                    debug,
                    conversation_state,
                ],
            )

            message.submit(
                fn=ui_music_agent_chat,
                inputs=[
                    message,
                    conversation_state,
                    force_answer,
                    use_web_search,
                    enable_critic,
                    search_context_size,
                ],
                outputs=[
                    transcript,
                    message,
                    debug,
                    conversation_state,
                ],
            )

            clear.click(
                fn=ui_clear_chat,
                inputs=[],
                outputs=[
                    transcript,
                    message,
                    debug,
                    conversation_state,
                ],
            )

        with gr.Tab("Audio → Language"):
            audio_in = gr.Audio(
                type="filepath",
                label="Upload audio",
            )

            analyze_btn = gr.Button("Analyze")

            rec_out = gr.Textbox(
                label="DJ description",
                lines=8,
            )

            top3_out = gr.Textbox(
                label="Top-3 predicted genres",
            )

            feat_out = gr.Textbox(
                label="Audio features",
            )

            analyze_btn.click(
                fn=ui_analyze_audio,
                inputs=audio_in,
                outputs=[
                    rec_out,
                    top3_out,
                    feat_out,
                ],
            )

    demo.queue().launch(
        share=True,
        show_error=True,
        debug=True,
    )

"""## Practical notes

- Use `run_music_ai_agent(...)` as the main entry point.
- This agent does not depend on the local GTZAN catalog for recommendations.
- The local GTZAN model is still useful for `Audio → Language`, but real-song recommendation is handled by the API-backed agent.
- To avoid unnecessary clarification loops, `force_answer=True` is the default. The agent will state assumptions and answer.
- Web search requires a valid `OPENAI_API_KEY`.

"""